<?php
/**
 * @license Copyright 2016-2018 CryptoMarket Inc., MIT License
 * @see https://github.com/cryptomkt/magento-plugin/blob/master/LICENSE
 */

/**
 * @see Cryptomarket_Core_Block_Adminhtml_System_Config_Form_Field_Header
 */
 
echo '<div style="padding:9px 4px">' .
        '<img src="https://www.cryptocompra.com/img/logo.png" alt="CryptoMarket" witdth="263" height="34" />' .
     '</div>';
?>
