<?php
/**
 * @license Copyright 2016-2018 CryptoMarket Inc., MIT License
 * @see https://github.com/cryptomkt/magento-plugin/blob/master/LICENSE
 */

/**
 * @see Cryptomarket_Core_Block_Form_Cryptomarket
 */

$_code = $this->getMethodCode();
// if (Mage::getStoreConfig('payment/cryptomarket/fullscreen')) {
	echo '<ul class="form-list" id="payment_form_' . $_code . '">' .
	         '<li>You will be transfered to <a href="https://cryptomkt.com" target="_blank">CryptoMarket</a> to complete your purchase.</li>' .
	     '</ul>';
// }
?>
